[workspace]
members = [
  "cycles-withdraw",
  "ic-factory",
  "ic-helpers",
  "ic-storage",
  "ic-storage/ic-storage-derive",
  "ic-canister/ic-canister",
  "ic-canister/ic-canister-macros",
  "tests/proto-factory",
  "tests/canister-a",
  "tests/canister-b",
  "tests/canister-c",
]

